import Head from 'next/head';
import Image from "next/image";
import {Courier_Prime} from "next/font/google";

import {useGetChuckNorrisJokeQuery} from "@/store/chuckNorrisRandomJoke/chuckNorrisJoke.api";

import chuck_gif from '../../public/assets/chuck-gif.gif';

const courierPrime = Courier_Prime({subsets: ['latin'], weight: '400'})

export default function Home() {

  const {data, isLoading, refetch} = useGetChuckNorrisJokeQuery(undefined, {pollingInterval: 10000})

  return (
    <>
      <Head>
        <title>Chuck Norris Jokes</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main
        className={`${courierPrime.className} w-[100%] absolute top-[50%] left-[50%] translate-x-[-50%] translate-y-[-50%]`}>
        <h1 className='text-4xl text-center mb-4 pr-4 pl-4'>Chuck Norris Jokes</h1>
        <div className='text-center'>
          {isLoading ? <h3 className='text-center mb-4 pr-4 pl-4'>Loading...</h3> :
            <h3 className='text-center mb-4 pr-4 pl-4'>{data?.value}</h3>}
          <div className='mb-6 flex justify-center border-b-[1px] border-stone-700'>
            <Image src={chuck_gif} alt='Chuck Norris gif' unoptimized/>
          </div>
          <button
            type='button'
            onClick={refetch}
            className='py-2 px-8 bg-gray-400'
          >
            New Joke
          </button>
        </div>
      </main>
    </>
  )
}
